spring.application.name=Project2ConnectDb
spring.datasource.url = jdbc:postgresql://localhost:5432/msg_db
spring.datasource.username = postgres
spring.datasource.password = admin
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
